#!/usr/bin/env python3

# pyaklon shamefacedly comes crawling back to Python.
# It was fun writing naklo in Perl, but it grew difficult
# to maintain. Therefore...

from pyaFiles import controlFile, titleFile, listingFile
import argparse
import sys

MY_NAME = "pyaklon"


class pyaklon(object):

    def __init__(self, *args):
        args = self._prep_args(*args)

        try:
            # listing file (which also tells us how many files to
            # operate on
            errlevel = str("listingFile %s" % args.listing)
            self.listingFile = listingFile(args.listing, None)
            self.numFiles = self.listFile.countTagees()
            # titles file
            errlevel = str("titleFile %s" % args.titles)
            self.titleFile = titleFile(args.titles, self.numFiles)
            # control file
            errlevel = str("controlFile %s " % args.control)
            self.controlFile = controlFile(args.control, self.numFiles)
        except FileNotFoundError:
            errstr = str("%s was not found!" % errlevel)
            self.pyaErr(errstr, 1)

    def _prep_args(self, *args):
        ap = argparse.ArgumentParser()
        ap.add_argument("-l", "--listing",
                        help="name of listing file (typically "
                        "a shell redirect)",)
        ap.add_argument("-t", "--titles",
                        help="name of titles file",)
        ap.add_argument("-c", "--control",
                        help="name of control file",)
        args = ap.parse_args()

        compulsory = (args.listing
                      and args.titles
                      and args.control)
        if not compulsory:
            ap.print_help()
            errstr = ("\nHint: you probably want to provide all three "
                      "arguments. The listing file is typically a shell "
                      "redirect, like `<(ls ./*.flac)'.")
            self.pyaErr(errstr, 1)
        return args

    def pyaErr(self, msg, bailcode=None):
        sys.stderr.write("%s\n" % msg)
        if bailcode is not None:
            sys.exit(bailcode)

    def checkSanity(self):
        fileInsanity = None
        for fl in (self.listingFile, self.titleFile, self.controlFile):
            fileInsanity = fileInsanity or fl.checkInsanity()
        if fileInsanity:
            self.pyaErr(str(fileInsanity), 1)

    def main(self):
        self.checkSanity()
        return 0


if __name__ == "__main__":
    runner = pyaklon(*sys.argv[1:])
    sys.exit(runner.main())
